@startuml

abstract class AbstractList
abstract AbstractCollection
interface List
interface Collection

List <|-- AbstractList
Collection <|-- AbstractCollection

Collection <|- List
AbstractCollection <|- AbstractList
AbstractList <|-- ArrayList

class ArrayList {
Object[] elementData
size()
}

enum TimeUnit {
DAYS
HOURS
MINUTES
}

@enduml

@startuml
'PlantUML
Class Singleton {
uniqueInstance
getInstance()
}

Singleton <|--CoolerSingleton
Singleton <|--HotterSingleton

Class CoolerSingleton {
}
Class HotterSingleton {
}

CoolerSingleton <-- SingletonTestDrive
HotterSingleton <-- SingletonTestDrive
Class SingletonTestDrive{

}
@enduml
